config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  
  devise_for :users,controllers: {
        #sessions: 'users/sessions'
        registrations: 'users/registrations'
  },
  :path_prefix => 'my' 
  resources :users

  resources :books
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  attr_accessor :remove_image
  has_one_attached :image, dependent: :destroy
  has_many :books, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence:true, uniqueness:true
  validates :unique_id, presence:true, uniqueness:true ,format: { with: /\A(\b[A-Z]+\s+\d{1,9})*\z/, message: "please enter keywords in correct format"}
  #before_save :uppercase_id
  after_create :assign_default_role
  def uppercase_id
    self[:unique_id] = self.unique_id.upcase
  end
  # def assign_default_role
  #   self.add_role(:reader) if self.roles.blank?
  # en
  

  def assign_default_role
     if self.roles.blank?
      ch = unique_id.split(" ")
      if ch[0]=="AU" || ch[0]=="au"
        self.add_role(:author)
      # elsif ch[0]== "VIP" || ch[0]=="vip" 
      #   self.add_role(:vip)
      else
        self.add_role(:reader)
      end
     end
  end



  attr_writer :login

  def login
    @login || self.username || self.email || self.unique_id
  end

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if (login = conditions.delete(:login))
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value OR lower(unique_id) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email) || conditions.has_key?(:unique_id)
        where(conditions.to_h).first
      end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  protected
  
 def update_resource(resource, params)
    # Require current password if user is trying to change password.
    return super if params["password"]&.present?

    # Allows user to update registration information without password.
    resource.update_without_password(params.except("current_password"))
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @books = Book.all
    #@user= User.find_by(id: current_user.id)    
  end
  def show
    #debugger
    @user =User.find(params[:id])
    @books = @user.books

  end
   def destroy
    @user = User.find(params[:id])
    @user.destroy
    if @user.destroy
      redirect_to root_url, notice: "User deleted."
    end
  end
  def edit
     @user = User.find(params[:id])
    
  end


   def update
     @user = User.find(params[:id])
     if @user.update(user_params)
       redirect_to root_path
     else
       render 'edit'
     end
   end

   private

   def user_params
     params.require(:user).permit(:username, :email,:image,:remove_image, :unique_id, :password, :password_confirmation, :remember_me)
   end
   def set_user
    @User = User.find(params[:id])
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<% if user.id !=current_user.id%>
<% if user.roles.first.name != "admin" %>
<%# if user.roles.first.name == "author"%>
<tr>
	<% if user.image.attached? %>
	<td align="center"><%= image_tag user.image.representation(resize_to_limit: [70, 70]) %></td> 
	<% end %> 
	<% if current_user.has_role? :admin %>
	<td><%= user.unique_id %></td>
	<%end%>
	<td><%= user.username %></td>
	<td><%= user.email %></td>
	<td><%= link_to "Show", user %></td>
	<% if current_user.has_role? :admin %>
	
	<td><%= link_to "Edit", edit_user_path(user) %></td>
	<td><%= link_to "delete", user, method: :delete,remote: true,data: { confirm: 'Are you sure?' }%></td>
	<%end%>
	<%end%>
	<%#end%>

	<%end%><!--ending name matching-->
</tr>

app/views/users/destroy.js.erb
$("td#<%= user.username %>").remove();

app/views/users/edit.html.erb
<h2>Edit <%#= resource_name.to_s.humanize %></h2>

<%= form_for(@user) do |f| %>
  <%#= render "devise/shared/error_messages", resource: resource %>
  <div class="field">
    <%= f.label :Username %><br />
    <%= f.text_field :username, autofocus: true, placeholder:"Rocky@1234" %>
  </div>
  <div class="field">
    <%= f.label :Unique_id %><br />
    <%= f.text_field :unique_id, placeholder:"D1234" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <!-- image -->
        <fieldset class="field">
          <legend><strong>Image</strong></legend>
          <%= f.file_field :image %>
        </fieldset>
  


  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>


<%= link_to "Back", root_path %>

app/views/users/index.html.erb
<fieldset align = "center">
<% if user_signed_in? %>
	<legend align='center'>Logged in as <strong><%= current_user.username %></strong><br><strong><%=current_user.roles.first.name%></strong></legend>
	<p align="center"><%= link_to "Show Profile", current_user %></p>
  <p align="center"><%= link_to 'Edit profile', edit_user_registration_path %></p>
  <p align="center"><%= link_to "Logout", destroy_user_session_path, method: :delete  %></p>
</fieldset> 
<!-- User data import-->
<% if current_user.has_role? :author or current_user.has_role? :admin %>
<fieldset align = "center">
	<legend><strong>>  User List  <</strong></legend>
	<table align="center">
		<thead>
			<tr>

				<th>Image</th>
				
				<th align="center"> Username </th>
				<th align="center"> Email </th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody id='users'>
			<%= render @users %>
		</tbody>


	</table>
</fieldset>
<%end%>
<br>
<!-- author and reader view -->
<fieldset>
			<p align="center"><%= link_to "Book List",books_path %></p>
</fieldset>
 
<!-- Ending of login -->

<%else%>
  <legend align = "center">For Sign Up and Login</legend>
    <p align="center"><%= link_to "Sign up", new_user_registration_path  %></p>
    <p align="center"><%= link_to "Login", new_user_session_path  %></p>
<%end%>
</fieldset>

app/views/users/show.html.erb
 
<fieldset align="center"><fieldset>
   <legend align ="center"><h2> User Detail :</h2></legend>

   <% if current_user.image.attached? %>
   <p align="center"><%= image_tag current_user.image.representation(resize_to_limit: [250, 250]) %></p> 
   <% end %> 
   <p align ="center"><strong> Username : </strong> <%= @user.username%></p>
   <p align ="center"><strong> Email    : </strong> <%= @user.email %></p>
</fieldset>


<% if @user.books != []%>
<% @books.each do |book| %>
<fieldset>
    <p align="center"><strong> Name      : </strong><%=book.name%></p>
    <p align="center"><strong> Edition   : </strong><%=book.edition%></p>
    <p align="center"><strong> Released  : </strong><%=book.r_year%></p>
    <p align="center"><strong> Price     : </strong><%=book.price%></p>

</fieldset>
<br>
<%end%>
<%end%>
<fieldset>
    <p align="center" ><%= link_to "back",root_path %></p>


</fieldset>